import FavoriteButton from "../FavoriteButton/favoriteButton";
import { RiEarthFill } from "react-icons/ri";
export const SlickData = [
  {
    faurat: <FavoriteButton />,
    title: "1bhk",
    task: "Fix Price",
    price: "₹5.0 Cr",
    address: "South Delhi Luxury",
    para: "GK I, New Delhi",
    cName: "card",
  },
  {
    faurat: <FavoriteButton />,
    title: "2bhk",
    task: "Fix Price",
    price: "₹5.0 Cr",
    address: "South Delhi Luxury",
    para: "GK I, New Delhi",
    class: "card",
  },
  {
    faurat: <FavoriteButton />,
    title: "3bhk",
    task: "Fix Price",
    price: "₹5.0 Cr",
    address: "South Delhi Luxury",
    para: "GK I, New Delhi",
    class: "card",
  },
  {
    faurat: <FavoriteButton />,
    title: "4bhk",
    task: "Fix Price",
    price: "₹5.0 Cr",
    address: "South Delhi Luxury",
    para: "GK I, New Delhi",
    class: "card",
  },
  {
    faurat: <FavoriteButton />,
    title: "5bhk",
    task: "Fix Price",
    price: "₹5.0 Cr",
    address: "South Delhi Luxury",
    para: "GK I, New Delhi",
    class: "card",
  },
  {
    faurat: <FavoriteButton />,
    title: "6bhk",
    task: "Fix Price",
    price: "₹5.0 Cr",
    address: "South Delhi Luxury",
    para: "GK I, New Delhi",
    class: "card",
  },
  {
    faurat: <FavoriteButton />,
    title: "4bhk",
    task: "Fix Price",
    price: "₹5.0 Cr",
    address: "South Delhi Luxury",
    para: "GK I, New Delhi",
    class: "card",
  },
  {
    faurat: <FavoriteButton />,
    title: "8bhk",
    task: "Fix Price",
    price: "₹5.0 Cr",
    address: "South Delhi Luxury",
    para: "GK I, New Delhi",
    class: "card",
  },
];

export const SmallData = [
  {
    title: "Delhi",
    btn: "6345 Properties for Sale",
    mony: "₹15 Lac | 435 sqft",
    btns: <RiEarthFill />,
  },
  {
    title: "Pune",
    btn: "6345 Properties for Sale",
    mony: "₹15 Lac | 435 sqft",
    btns: <RiEarthFill />,
  },
  {
    title: "Munbai",
    btn: "6345 Properties for Sale",
    mony: "₹15 Lac | 435 sqft",
    btns: <RiEarthFill />,
  },
  {
    title: "Gurugram",
    btn: "6345 Properties for Sale",
    mony: "₹15 Lac | 435 sqft",
    btns: <RiEarthFill />,
  },
  {
    title: "Nashik",
    btn: "6345 Properties for Sale",
    mony: "₹15 Lac | 435 sqft",
    btns: <RiEarthFill />,
  },
];
